image: docker:latest
stages:
  - build
  - deploy
# push to develop for build image bellow for testing
build_dev:
  stage: build
  allow_failure: false
  script:
    - echo 'Start building website ngs'
    - pwd
    - docker stop web-ngs-landing-test || true && docker rm web-ngs-landing-test || true
    - docker build -t web-ngs-landing-test:v1.0 -f Dockerfile.dev .
    - docker run -d --restart=always -it -p 3311:3000 --name web-ngs-landing-test web-ngs-landing-test:v1.0
    - echo 'build done!'

  only:
    - develop
    - /^dev-.*$/
deploy_dev:
  stage: deploy
  environment:
    name: development
  script:
    - echo 'script for deploying on DEV'
    - pwd
    - echo 'DEPLOYED SUCCESSFULLY'
  only:
    - develop
    - /^dev-.*$/
# mutiple env build here

