FROM node:16-alpine

RUN mkdir -p /usr/src/app
ENV PORT 3000

WORKDIR /usr/src/app

COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app

# Enviroment for customer

RUN yarn install 

COPY . /usr/src/app

RUN yarn build:uat

EXPOSE 3000
CMD ["yarn", "start"]